export const genderOptions = ["Male", "Female", "Other"]
export const bodyOptions = ["Thin", "Curve", "Fit", "Muscular"]
export const hairOptions = ["Brunette", "Black", "Blond", "Reddish", "Gray"]
export const eyesOptions = ["Green", "Blue", "Brown"]
export const skillsOptions = ["Dancing", "Singing", "Musician", "Mimic", "Acrobatics", "Clowning"]
export const languagesOptions = ["English", "Spanish", "French", "Arabic", "Italian", "German", "Russian"]
